language: node_js
addons:
  chrome: stable
node_js:
  - "8"
  - "10"
  - "12"
env:
  - WEBPACK_VERSION=4
  - WEBPACK_VERSION=3
script: yarn lint && yarn add --dev webpack@$WEBPACK_VERSION && yarn test
